### ISSUE TITLE
Dejo de funcionar la Api en python

### ISSUE THREAD

**Issue by JorgeCuauro** [fcoagz/pyBCV#2]
Ante todo agradezco por desarrollar excelente proyecto de publicar las tasas activas del portal de BCV. Me ha sido extremadamente util para un proyecto en la universidad. Ahora luego de implementarlo hace como dos meses, funcionó perfetamente pero ahora me arroja este error: 
HTTPSConnectionPool(host='www.bcv.org.ve', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

Cual podria ser la solución corregir ese incidente?

Agradeciendo de antemano su tiempo y gestión.

**Comment by fcoagz** [comment]
Buenos días Jorge, muchísimas gracias. El problema ha corrido debido a los certificados SSL de la página de BCV, en unos instante corregiré esa parte.

Mientras tanto puede usar pyDolarVenezuela, es mi segunda biblioteca en el cuál te permite obtener datos de los monitores de diversas páginas web informativa sobre el valor actual del dólar y/o euro. Para obtener los datos del Banco Central de Venezuela, puede usar el siguiente código:

```python
from pyDolarVenezuela.pages import BCV
from pyDolarVenezuela import Monitor 

monitor = Monitor(BCV)

tasas_de_cambio = monitor.get_value_monitors()
```

Acá obtienes todas las tasas de cambio del BCV, te ofrece varias entidades incluyendo el `title`, `price`, `last_update`. Aunque además podés asignarle argumentos a la función para obtener una tasa en específico:

```from pyDolarVenezuela.pages import BCV 
from pyDolarVenezuela import Monitor

monitor = Monitor(BCV)

valor_euro = monitor.get_value_monitors("eur", "price")

print(valor_euro)```

Te recomiendo leer la documentación: https://github.com/fcoagz/pydolarvenezuela

**Comment by fcoagz** [comment]
Buenos días Jorge, muchísimas gracias. El problema ha corrido debido a los certificados SSL de la página de BCV, en unos instante corregiré esa parte.

Mientras tanto puede usar pyDolarVenezuela, es mi segunda biblioteca en el cuál te permite obtener datos de los monitores de diversas páginas web informativa sobre el valor actual del dólar y/o euro. Para obtener los datos del Banco Central de Venezuela, puede usar el siguiente código:

```python
from pyDolarVenezuela.pages import BCV
from pyDolarVenezuela import Monitor 

monitor = Monitor(BCV)

tasas_de_cambio = monitor.get_value_monitors()
```

Acá obtienes todas las tasas de cambio del BCV, te ofrece varias entidades incluyendo el `title`, `price`, `last_update`. Aunque además podés asignarle argumentos a la función para obtener una tasa en específico:

```from pyDolarVenezuela.pages import BCV 
from pyDolarVenezuela import Monitor

monitor = Monitor(BCV)

valor_euro = monitor.get_value_monitors("eur", "price")

print(valor_euro)```

Te recomiendo leer la documentación: https://github.com/fcoagz/pydolarvenezuela 

Ahora no estoy en casa, en cuanto llegue lo acomodare

**Comment by fcoagz** [comment]
pyBCV fue actualizada hace un momento! @JorgeCuauro

**Comment by JorgeCuauro** [comment]
Agradecido Francisco!!.
Excelente aporte a la comunidad emprendedora en BackEnd - Python

Voy a seguir tus indicaciones.

**Comment by fcoagz** [comment]
Siempre a la orden
